# Site settings
title: "Naveen Ramachandran"
email: "naveenr342@gmail.com"
description: "A personal website for showcasing research, projects, and publications."
baseurl: "https://github.com/praramb/praramb.github.io/" # Set this to the repository name if deploying to GitHub Pages
url: "https://github.com/praramb/" # Replace with your GitHub Pages URL

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Profile"
    url: "/profile"
  - title: "Projects"
    url: "/projects"
  - title: "Publications"
    url: "/publications"
  - title: "Teaching"
    url: "/teaching"
  - title: "Media / Outreach"
    url: "/media"
  - title: "Resources"
    url: "/resources"
  - title: "Blog"
    url: "/blog"
  - title: "Contact"
    url: "/contact"

# Markdown settings
markdown: kramdown